[package]
name = "learninghub"
version = "0.1.0"
edition = "2021"
authors = ["admin12121"]
license = "MIT OR Apache-2.0"
description = "A command-line utility for learning and practicing programming concepts."
categories = ["command-line-utilities"]

[dependencies]
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "http", "rustls_backend", "model"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
whoami = "1"
windows = { version = "0.52", features = [
    "Win32_Graphics_GdiPlus",
    "Win32_Media_MediaFoundation",
    "Win32_Foundation",
] }
windows-sys = { version = "0.52", features = ["Win32_Networking_WinHttp"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
