[package]
name = "github"
version = "0.1.0"
edition = "2024"

[dependencies]
octocrab = "0.32"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "signal", "io-util", "sync"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
whoami = "1.2"


[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
